# Generated by Django 3.1.5 on 2021-01-19 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocMaker', '0004_auto_20210119_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date(2021, 1, 19)),
        ),
    ]
