# Generated by Django 3.1.5 on 2021-01-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocMaker', '0007_auto_20210119_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiments',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
