# Generated by Django 3.1.5 on 2021-01-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocMaker', '0008_auto_20210119_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiments',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
