# Generated by Django 3.1.5 on 2021-01-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocMaker', '0010_auto_20210121_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiments',
            name='aim',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='experiments',
            name='source_code',
            field=models.TextField(max_length=10000),
        ),
    ]
